image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy_coverage
  - build

test:
  stage: test
  tags:
    - docker
  image: node
  script:
    - yarn
    - yarn test
  artifacts:
    paths:
      - coverage/

coverage:
  stage: deploy_coverage
  dependencies:
    - test
  tags:
    - docker
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

build:
  stage: build
  tags: 
    - docker
  script:
    - docker build -t wishlist-api -f ./Dockerfile.production .
  only:
    - master