image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  tags:
    - docker
  image: node
  script:
    - yarn
    - yarn test

build:
  stage: build
  tags: 
    - docker
  script:
    - docker build -t wishlist-api -f ./Dockerfile.production .
  only:
    - master