version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/usr/src/app
    ports:
      - '3000:80'
    environment:
      - DB_URI=mongo
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db