version: '3'

services:
  api:
    build: .
    ports:
      - '3000:80'
    environment:
      - DB_URI=mongo
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db